version: '3'

services:
  logs_template: &logs_template
    image: alpine
    logging:
      options:
        max-size: "200k"
        max-file: "1"


  pg:
    <<: *logs_template
    image: postgres:12.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5433:5432"

networks:
  default: {}